name: ci

on: [push, pull_request]

jobs:
  build:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: download deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.27.1

      - name: check format
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check

      - name: check linting
        if: matrix.os == 'ubuntu-latest'
        run: deno lint
      
      - name: run tests
        run: deno task test